---
- hosts: all 
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Specify the path to Python 3 interpreter
    mysql_database: skillsmatrix_db # Set the desired name for the database
    mysql_root_password: supersecure  # Set the desired root password for MySQL
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes

    - name: Install APT apps 
      apt:
        name: 
          - net-tools
        state: present

    - name: Install Java 19
      apt:
        name: openjdk-19-jdk
        state: present

    - name: Install Python 3
      apt:
        name: 
        - python3
        - python3-pip
        - python3-botocore
        - python3-boto3
        state: present

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present
      vars:
        mysql_user: myuser  # Set the desired username for the new MySQL user
        mysql_password: mypassword  # Set the desired password for the new MySQL user

    - name: Install pymysql
      pip:
        name: pymysql
        state: present
        executable: pip3

    - name: Create database skillsmatrix_db 
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
        name: "{{ mysql_database }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create user smdbuser
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
        name: smdbuser
        password: supersecure

    - name: Grant privileges to smdbuser
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
        name: smdbuser 
        password: supersecure
        priv: "*.*:ALL"
        host: localhost
        append_privs: yes

- name: Ensure /opt/app directory exists
  hosts: vm01
  become: true
  tasks:
    - name: Create /opt/app directory if it doesn't exist
      file:
        path: /opt/app
        state: directory
        mode: '0755'

    - name: Pull JAR file from S3
      aws_s3:
        bucket: savvato-builds-bucket 
        object: skills-matrix-api.jar
        dest: /opt/app/skills-matrix-api.jar
        mode: get

    - name: Copy systemd service file
      copy:
        src:  skills-matrix-api.service
        dest: /etc/systemd/system/skills-matrix-api.service

    - name: Enable and start the service
      systemd:
        name: skills-matrix-api.service
        state: started
        enabled: yes

    - name: Run JAR file in the background
      shell: java -jar /opt/app/skills-matrix-api.jar > /opt/app/server.log 2>&1 &
      async: 60
      poll: 0
      register: jar_execution


